INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Fiesta', 'Ford', 2020, 'Atualmente, se encontra em sua sétima geração', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Strada', 'Fiat', 2019, 'A Nova Fiat Strada tem a força e a capacidade de carga que todo produtor rural precisa.', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Tracker', 'Chevrolet', 2021, 'O novo SUV conta com tecnologia Wi-Fi nativa', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Mustang', 'Ford', 2015, 'Motor V8 de 466 cavalos de potência, câmbio automático de 10 marchas e tração traseira.', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Gol', 'Volkswagen', 2009, 'Desenhado no Brasil e comercializado em vários países', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Onix', 'Chevrolet', 2021, 'O novo carro hatch com Wi-Fi da Chevrolet', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Logan', 'Renault', 2008, 'Compacto e moderno', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Saveiro', 'Volkswagen', 2015, 'Saveiro pronta para tudo', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Fusion', 'Ford', 2010, 'O Ford Fusion que foi vendido aqui no Brasil', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Camaro', 'Chevrolet', 1999, 'O melhor carro esportivo da Chevrolet!', false, NOW());

INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Fiesta', 'Ford', 2020, 'Atualmente, se encontra em sua sétima geração', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Strada', 'Fiat', 2019, 'A Nova Fiat Strada tem a força e a capacidade de carga que todo produtor rural precisa.', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Tracker', 'Chevrolet', 2021, 'O novo SUV conta com tecnologia Wi-Fi nativa', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Mustang', 'Ford', 2015, 'Motor V8 de 466 cavalos de potência, câmbio automático de 10 marchas e tração traseira.', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Gol', 'Volkswagen', 2009, 'Desenhado no Brasil e comercializado em vários países', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Onix', 'Chevrolet', 2021, 'O novo carro hatch com Wi-Fi da Chevrolet', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Logan', 'Renault', 2008, 'Compacto e moderno', false, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Saveiro', 'Volkswagen', 2015, 'Saveiro pronta para tudo', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Fusion', 'Ford', 2010, 'O Ford Fusion que foi vendido aqui no Brasil', true, NOW());
INSERT INTO tb_veiculo (veiculo, marca, ano, descricao, vendido, created) VALUES ('Camaro', 'Chevrolet', 1999, 'O melhor carro esportivo da Chevrolet!', false, NOW());